In [15]:
#판다스 실습

In [17]:
import pandas as pd

In [19]:
order_items_df = pd.read_csv("archive/order_items.csv")

In [20]:
order_items_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   order_id          112650 non-null  object
 1   order_item_id     112650 non-null  int64
 2   product_id        112650 non-null  object
 3   seller_id         112650 non-null  object
 4   price             112650 non-null  float64
 5   shipping_charges  112650 non-null  float64
dtypes: float64(2), int64(1), object(3)
memory usage: 5.2+ MB

In [23]:
order_items_df.isnull().sum()

order_id            0
order_item_id       0
product_id          0
seller_id           0
price               0
shipping_charges    0
dtype: int64

In [25]:
payment_df = pd.read_csv("archive/payments.csv")

In [27]:
payment_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [29]:
payment_df.duplicated().sum()

0

In [31]:
order_items_df.duplicated().sum()

0

In [33]:
customers_df = pd.read_csv("archive/customers.csv")

In [35]:
customers_df.duplicated().sum()

3089

In [37]:
#customers.csv 결측치 확인
customers_df.isnull().sum()

customer_id                 0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [39]:
#orders.csv 불러오기
orders_df = pd.read_csv("archive/orders.csv")

In [40]:
#orders.csv 결측치 확인
orders_df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_timestamp        2965
order_estimated_delivery_date       0
dtype: int64

In [43]:
#orders.csv 정보 확인
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_timestamp      96476 non-null  object
 6   order_estimated_delivery_date  99441 non-null  object
dtypes: object(7)
memory usage: 5.3+ MB

In [45]:
#products.csv 데이터 가져오기
products_df = pd.read_csv("archive/products.csv")

In [47]:
#products.csv 정보 확인
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             32951 non-null  object
 1   product_category_name  32781 non-null  object
 2   product_weight_g       32949 non-null  float64
 3   product_length_cm      32949 non-null  float64
 4   product_height_cm      32949 non-null  float64
 5   product_width_cm       32949 non-null  float64
dtypes: float64(4), object(2)
memory usage: 1.5+ MB

In [49]:
#products.csv 결측치 확인
products_df.isnull().sum()

product_id                 0
product_category_name    170
product_weight_g           2
product_length_cm          2
product_height_cm          2
product_width_cm           2
dtype: int64

In [51]:
#null 값이 한 개 이상인 데이터만 보고샆은 경우(전체열)
products_df ["missing_count"] = products_df.isnull().sum(axis =1)

In [53]:
#필터링
filtered_df = products_df[products_df["missing_count"] > 0]

In [55]:
#출력
filtered_df

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,missing_count
105,a41e356c76fab66334f36de622ecbd3a,NaN,650.0,17.0,14.0,12.0,1
128,d8dee61c2034d6d075997acef1870e9b,NaN,300.0,16.0,7.0,20.0,1
145,56139431d72cd51f19eb9f7dae4d1617,NaN,200.0,20.0,20.0,20.0,1
154,46b48281eb6d663ced748f324108c733,NaN,18500.0,41.0,30.0,41.0,1
197,5fb61f482620cb672f5e586bb132eae9,NaN,300.0,35.0,7.0,12.0,1
...,...,...,...,...,...,...,...
8230,fe34503c6bccf918db601aaafd4a975a,NaN,3000.0,16.0,21.0,19.0,1
8291,0c877471e35049402bca235e06cb8063,NaN,10750.0,34.0,20.0,30.0,1
8332,1574ed2c73e4465c572f68dd77528203,NaN,16000.0,58.0,28.0,58.0,1
8578,09ff539a621711667c43eba6a3bd8466,toys,NaN,NaN,NaN,NaN,4
18851,5eb564652db742ff8f28759cd8d2652a,toys,NaN,NaN,NaN,NaN,4

In [57]:
#겹치는 값 확인
products_df.duplicated().sum()

0

In [59]:
import pandas as pd

#orders 데이터프레임
orders_df = pd.DataFrame({
    'order_id': [1,2,3],
    'customer_id': [101,102,103],
    'order_total': [150,200,300]
})

#customers 데이터프레임
customers_df = pd.DataFrame ({
    'customer_id': [101,102,103,104],
    'customer_name': ['Alice','Alicia','Bob','Charlie']
})

print("orders DataFrame:")
print(orders_df)
print("\ncustomers DataFrame:")
print(customers_df)

#Left Join 수행
merged_df = pd.merge(orders_df, customers_df, on = 'customer_id', how = 'left')

print("\nMerged DataFrame (LEFT JOIN 결과):")
print(merged_df)

orders DataFrame:
   order_id  customer_id  order_total
0         1          101          150
1         2          102          200
2         3          103          300

customers DataFrame:
   customer_id customer_name
0          101         Alice
1          102        Alicia
2          103           Bob
3          104       Charlie

Merged DataFrame (LEFT JOIN 결과):
   order_id  customer_id  order_total customer_name
0         1          101          150         Alice
1         2          102          200        Alicia
2         3          103          300           Bob

In [61]:
merged_df.duplicated().sum()

0

In [63]:
#중복치 확인
customers_df.duplicated().sum()

0

In [70]:
customers_df = customers_df.drop_duplicates()

In [72]:
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    4 non-null      int64
 1   customer_name  4 non-null      object
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

In [74]:
customers_df.duplicated().sum()

0

In [25]:
import pandas as pd

In [117]:
customers_df = pd.read_csv("archive/customers.csv")
customers_df = customers_df.drop_duplicates()
order_items_df = pd.read_csv("archive/order_items.csv")
orders_df = pd.read_csv("archive/orders.csv")
payments_df = pd.read_csv("archive/payments.csv")
products_df = pd.read_csv("archive/products.csv")

print(payments_df.duplicated().sum())
print(payments_df.isnull().sum())
print(order_items_df.duplicated().sum())
print(order_items_df.isnull().sum())
print(orders_df.duplicated().sum())
print(orders_df.isnull().sum())

print(payments_df.info())
print(order_items_df.info())
print(orders_df.info())

0
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64
0
order_id            0
order_item_id       0
product_id          0
seller_id           0
price               0
shipping_charges    0
dtype: int64
0
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_timestamp        2965
order_estimated_delivery_date       0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   order_id          112650 non-null  object
 1   order_item_id     112650 non-null  int64
 2   product_id        112650 non-null  object
 3   seller_id         112650 non-null  object
 4   price             112650 non-null  float64
 5   shipping_charges  112650 non-null  float64
dtypes: float64(2), int64(1), object(3)
memory usage: 5.2+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_timestamp      96476 non-null  object
 6   order_estimated_delivery_date  99441 non-null  object
dtypes: object(7)
memory usage: 5.3+ MB
None

In [37]:
merged = pd.merge(orders_df, payments_df, how = 'left', on = 'order_id')
merged = pd.merge(merged, customers_df, how = 'left', on = 'customer_id')
merged = pd.merge(merged, order_items_df, how = 'left', on = 'order_id')
merged = pd.merge(merged, products_df, how = 'left', on = 'product_id')

In [39]:
merged.duplicated().sum()

0

In [41]:
merged.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 178
order_delivered_timestamp        3422
order_estimated_delivery_date       0
payment_sequential                  3
payment_type                        3
payment_installments                3
payment_value                       3
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
order_item_id                     835
product_id                        835
seller_id                         835
price                             835
shipping_charges                  835
product_category_name            1267
product_weight_g                  855
product_length_cm                 855
product_height_cm                 855
product_width_cm                  855
dtype: int64

In [45]:
merged = merged.dropna()
merged.isnull().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_timestamp        0
order_estimated_delivery_date    0
payment_sequential               0
payment_type                     0
payment_installments             0
payment_value                    0
customer_zip_code_prefix         0
customer_city                    0
customer_state                   0
order_item_id                    0
product_id                       0
seller_id                        0
price                            0
shipping_charges                 0
product_category_name            0
product_weight_g                 0
product_length_cm                0
product_height_cm                0
product_width_cm                 0
dtype: int64

In [59]:
grouped_1 = merged.groupby(by = ["order_id","order_item_id"]).agg({"price": "mean", "shipping_charges": "mean"})

In [61]:
grouped_1

                                                 price  shipping_charges
order_id                         order_item_id
00010242fe8c5a6d1ba2dd792cb16214 1.0             58.90             13.29
00018f77f2f0320c557190d7a144bdd3 1.0            239.90             19.93
000229ec398224ef6ca0657da4fc703e 1.0            199.00             17.87
00024acbcdf0a6daa1e931b038114c75 1.0             12.99             12.79
00042b26cf59d7ce69dfabb4e55b4fd9 1.0            199.90             18.14
...                                                ...               ...
fffc94f6ce00a00581880bf54a75a037 1.0            299.99             43.41
fffcd46ef2263f404302a634eb57f7eb 1.0            350.00             36.53
fffce4705a9662cd70adb13d4a31832d 1.0             99.90             16.95
fffe18544ffabc95dfada21779c9644f 1.0             55.99              8.72
fffe41c64501cc87c801fd61db3f6244 1.0             43.00             12.79

[109785 rows x 2 columns]

In [65]:
grouped_1 = grouped_1.groupby(by = ["order_id"]).agg({"price":"sum","shipping_charges":"sum"})

In [69]:
grouped_1

                                   price  shipping_charges
order_id
00010242fe8c5a6d1ba2dd792cb16214   58.90             13.29
00018f77f2f0320c557190d7a144bdd3  239.90             19.93
000229ec398224ef6ca0657da4fc703e  199.00             17.87
00024acbcdf0a6daa1e931b038114c75   12.99             12.79
00042b26cf59d7ce69dfabb4e55b4fd9  199.90             18.14
...                                  ...               ...
fffc94f6ce00a00581880bf54a75a037  299.99             43.41
fffcd46ef2263f404302a634eb57f7eb  350.00             36.53
fffce4705a9662cd70adb13d4a31832d   99.90             16.95
fffe18544ffabc95dfada21779c9644f   55.99              8.72
fffe41c64501cc87c801fd61db3f6244   43.00             12.79

[96139 rows x 2 columns]

In [75]:
grouped_2 = merged.groupby(by = ['order_id', 'payment_sequential']).agg({'payment_value':'mean'})
grouped_2 = grouped_2.groupby(by = ['order_id']).agg({'payment_value':'sum'})
grouped_2

                                  payment_value
order_id
00010242fe8c5a6d1ba2dd792cb16214          72.19
00018f77f2f0320c557190d7a144bdd3         259.83
000229ec398224ef6ca0657da4fc703e         216.87
00024acbcdf0a6daa1e931b038114c75          25.78
00042b26cf59d7ce69dfabb4e55b4fd9         218.04
...                                         ...
fffc94f6ce00a00581880bf54a75a037         343.40
fffcd46ef2263f404302a634eb57f7eb         386.53
fffce4705a9662cd70adb13d4a31832d         116.85
fffe18544ffabc95dfada21779c9644f          64.71
fffe41c64501cc87c801fd61db3f6244          55.79

[96139 rows x 1 columns]

In [77]:
grouped_merge = pd.merge(grouped_1, grouped_2, on = 'order_id', how='left')

In [79]:
grouped_merge

                                   price  shipping_charges  payment_value
order_id
00010242fe8c5a6d1ba2dd792cb16214   58.90             13.29          72.19
00018f77f2f0320c557190d7a144bdd3  239.90             19.93         259.83
000229ec398224ef6ca0657da4fc703e  199.00             17.87         216.87
00024acbcdf0a6daa1e931b038114c75   12.99             12.79          25.78
00042b26cf59d7ce69dfabb4e55b4fd9  199.90             18.14         218.04
...                                  ...               ...            ...
fffc94f6ce00a00581880bf54a75a037  299.99             43.41         343.40
fffcd46ef2263f404302a634eb57f7eb  350.00             36.53         386.53
fffce4705a9662cd70adb13d4a31832d   99.90             16.95         116.85
fffe18544ffabc95dfada21779c9644f   55.99              8.72          64.71
fffe41c64501cc87c801fd61db3f6244   43.00             12.79          55.79

[96139 rows x 3 columns]

In [87]:
(grouped_merge["price"] + grouped_merge["shipping_charges"] == grouped_merge["payment_value"]).sum()

76885

In [89]:
(grouped_merge["price"] + grouped_merge["shipping_charges"] != grouped_merge["payment_value"]).sum()

19254

In [93]:
#0 이상의 오차를 갖는 행의 개수
(grouped_merge["price"] + grouped_merge["shipping_charges"] - grouped_merge["payment_value"] >0).sum()

9525

In [97]:
(abs(grouped_merge["price"] + grouped_merge["shipping_charges"] - grouped_merge["payment_value"]) >0).sum()

19254

In [99]:
((grouped_merge["price"] + grouped_merge["shipping_charges"] != grouped_merge["payment_value"]) >0).sum()

19254

In [103]:
(abs(grouped_merge["price"] + grouped_merge["shipping_charges"] - grouped_merge["payment_value"]) >0.01).sum()

400

In [105]:
(abs(grouped_merge["price"] + grouped_merge["shipping_charges"] - grouped_merge["payment_value"]) >0.1).sum()

272

In [120]:
merged.isnull().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_timestamp        0
order_estimated_delivery_date    0
payment_sequential               0
payment_type                     0
payment_installments             0
payment_value                    0
customer_zip_code_prefix         0
customer_city                    0
customer_state                   0
order_item_id                    0
product_id                       0
seller_id                        0
price                            0
shipping_charges                 0
product_category_name            0
product_weight_g                 0
product_length_cm                0
product_height_cm                0
product_width_cm                 0
dtype: int64

In [122]:
merged.duplicated().sum()

0

In [156]:
#파생변수 만들기
merged["product_volume"] = merged["product_length_cm"] * merged["product_height_cm"] * merged["product_width_cm"]

In [158]:
merged.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date,payment_sequential,payment_type,payment_installments,...,product_id,seller_id,price,shipping_charges,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_volume
0,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,delivered,10/2/2017 10:56,2017-10-02 11:07:00,2017-10-10 21:25:00,2017-10-18,1.0,credit_card,1.0,...,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,8.72,housewares,500.0,19.0,8.0,13.0,1976.0
1,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,delivered,10/2/2017 10:56,2017-10-02 11:07:00,2017-10-10 21:25:00,2017-10-18,3.0,voucher,1.0,...,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,8.72,housewares,500.0,19.0,8.0,13.0,1976.0
2,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,delivered,10/2/2017 10:56,2017-10-02 11:07:00,2017-10-10 21:25:00,2017-10-18,2.0,voucher,1.0,...,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,8.72,housewares,500.0,19.0,8.0,13.0,1976.0
3,53cdb2fc8bc7dce0b6741e2150273451,af07308b275d755c9edb36a90c618231,delivered,7/24/2018 20:41,2018-07-26 03:24:00,2018-08-07 15:27:00,2018-08-13,1.0,wallet,1.0,...,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,118.70,22.76,toys,400.0,19.0,13.0,19.0,4693.0
4,47770eb9100c2d0c44946d9cf07ec65d,3a653a41f6f9fc3d2a113cf8398680e8,delivered,8/8/2018 8:38,2018-08-08 08:55:00,2018-08-17 18:06:00,2018-09-04,1.0,credit_card,3.0,...,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,159.90,19.22,toys,420.0,24.0,19.0,21.0,9576.0

In [160]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 115289 entries, 0 to 119159
Data columns (total 25 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       115289 non-null  object
 1   customer_id                    115289 non-null  object
 2   order_status                   115289 non-null  object
 3   order_purchase_timestamp       115289 non-null  object
 4   order_approved_at              115289 non-null  datetime64[ns]
 5   order_delivered_timestamp      115289 non-null  datetime64[ns]
 6   order_estimated_delivery_date  115289 non-null  datetime64[ns]
 7   payment_sequential             115289 non-null  float64
 8   payment_type                   115289 non-null  object
 9   payment_installments           115289 non-null  float64
 10  payment_value                  115289 non-null  float64
 11  customer_zip_code_prefix       115289 non-null  int64
 12  customer_city                  115289 non-null  object
 13  customer_state                 115289 non-null  object
 14  order_item_id                  115289 non-null  float64
 15  product_id                     115289 non-null  object
 16  seller_id                      115289 non-null  object
 17  price                          115289 non-null  float64
 18  shipping_charges               115289 non-null  float64
 19  product_category_name          115289 non-null  object
 20  product_weight_g               115289 non-null  float64
 21  product_length_cm              115289 non-null  float64
 22  product_height_cm              115289 non-null  float64
 23  product_width_cm               115289 non-null  float64
 24  product_volume                 115289 non-null  float64
dtypes: datetime64[ns](3), float64(11), int64(1), object(10)
memory usage: 22.9+ MB

In [162]:
merged["order_delivered_timestamp"] = pd.to_datetime(merged["order_delivered_timestamp"])

In [164]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 115289 entries, 0 to 119159
Data columns (total 25 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       115289 non-null  object
 1   customer_id                    115289 non-null  object
 2   order_status                   115289 non-null  object
 3   order_purchase_timestamp       115289 non-null  object
 4   order_approved_at              115289 non-null  datetime64[ns]
 5   order_delivered_timestamp      115289 non-null  datetime64[ns]
 6   order_estimated_delivery_date  115289 non-null  datetime64[ns]
 7   payment_sequential             115289 non-null  float64
 8   payment_type                   115289 non-null  object
 9   payment_installments           115289 non-null  float64
 10  payment_value                  115289 non-null  float64
 11  customer_zip_code_prefix       115289 non-null  int64
 12  customer_city                  115289 non-null  object
 13  customer_state                 115289 non-null  object
 14  order_item_id                  115289 non-null  float64
 15  product_id                     115289 non-null  object
 16  seller_id                      115289 non-null  object
 17  price                          115289 non-null  float64
 18  shipping_charges               115289 non-null  float64
 19  product_category_name          115289 non-null  object
 20  product_weight_g               115289 non-null  float64
 21  product_length_cm              115289 non-null  float64
 22  product_height_cm              115289 non-null  float64
 23  product_width_cm               115289 non-null  float64
 24  product_volume                 115289 non-null  float64
dtypes: datetime64[ns](3), float64(11), int64(1), object(10)
memory usage: 22.9+ MB

In [174]:
merged["order_approved_at"] = pd.to_datetime(merged["order_approved_at"])

In [176]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 115289 entries, 0 to 119159
Data columns (total 25 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       115289 non-null  object
 1   customer_id                    115289 non-null  object
 2   order_status                   115289 non-null  object
 3   order_purchase_timestamp       115289 non-null  object
 4   order_approved_at              115289 non-null  datetime64[ns]
 5   order_delivered_timestamp      115289 non-null  datetime64[ns]
 6   order_estimated_delivery_date  115289 non-null  datetime64[ns]
 7   payment_sequential             115289 non-null  float64
 8   payment_type                   115289 non-null  object
 9   payment_installments           115289 non-null  float64
 10  payment_value                  115289 non-null  float64
 11  customer_zip_code_prefix       115289 non-null  int64
 12  customer_city                  115289 non-null  object
 13  customer_state                 115289 non-null  object
 14  order_item_id                  115289 non-null  float64
 15  product_id                     115289 non-null  object
 16  seller_id                      115289 non-null  object
 17  price                          115289 non-null  float64
 18  shipping_charges               115289 non-null  float64
 19  product_category_name          115289 non-null  object
 20  product_weight_g               115289 non-null  float64
 21  product_length_cm              115289 non-null  float64
 22  product_height_cm              115289 non-null  float64
 23  product_width_cm               115289 non-null  float64
 24  product_volume                 115289 non-null  float64
dtypes: datetime64[ns](3), float64(11), int64(1), object(10)
memory usage: 22.9+ MB

In [178]:
merged["order_purchase_timestamp"] = pd.to_datetime(merged["order_purchase_timestamp"])

In [180]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 115289 entries, 0 to 119159
Data columns (total 25 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       115289 non-null  object
 1   customer_id                    115289 non-null  object
 2   order_status                   115289 non-null  object
 3   order_purchase_timestamp       115289 non-null  datetime64[ns]
 4   order_approved_at              115289 non-null  datetime64[ns]
 5   order_delivered_timestamp      115289 non-null  datetime64[ns]
 6   order_estimated_delivery_date  115289 non-null  datetime64[ns]
 7   payment_sequential             115289 non-null  float64
 8   payment_type                   115289 non-null  object
 9   payment_installments           115289 non-null  float64
 10  payment_value                  115289 non-null  float64
 11  customer_zip_code_prefix       115289 non-null  int64
 12  customer_city                  115289 non-null  object
 13  customer_state                 115289 non-null  object
 14  order_item_id                  115289 non-null  float64
 15  product_id                     115289 non-null  object
 16  seller_id                      115289 non-null  object
 17  price                          115289 non-null  float64
 18  shipping_charges               115289 non-null  float64
 19  product_category_name          115289 non-null  object
 20  product_weight_g               115289 non-null  float64
 21  product_length_cm              115289 non-null  float64
 22  product_height_cm              115289 non-null  float64
 23  product_width_cm               115289 non-null  float64
 24  product_volume                 115289 non-null  float64
dtypes: datetime64[ns](4), float64(11), int64(1), object(9)
memory usage: 22.9+ MB

In [182]:
merged["order_estimated_delivery_date"] = pd.to_datetime(merged["order_estimated_delivery_date"])

In [184]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 115289 entries, 0 to 119159
Data columns (total 25 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       115289 non-null  object
 1   customer_id                    115289 non-null  object
 2   order_status                   115289 non-null  object
 3   order_purchase_timestamp       115289 non-null  datetime64[ns]
 4   order_approved_at              115289 non-null  datetime64[ns]
 5   order_delivered_timestamp      115289 non-null  datetime64[ns]
 6   order_estimated_delivery_date  115289 non-null  datetime64[ns]
 7   payment_sequential             115289 non-null  float64
 8   payment_type                   115289 non-null  object
 9   payment_installments           115289 non-null  float64
 10  payment_value                  115289 non-null  float64
 11  customer_zip_code_prefix       115289 non-null  int64
 12  customer_city                  115289 non-null  object
 13  customer_state                 115289 non-null  object
 14  order_item_id                  115289 non-null  float64
 15  product_id                     115289 non-null  object
 16  seller_id                      115289 non-null  object
 17  price                          115289 non-null  float64
 18  shipping_charges               115289 non-null  float64
 19  product_category_name          115289 non-null  object
 20  product_weight_g               115289 non-null  float64
 21  product_length_cm              115289 non-null  float64
 22  product_height_cm              115289 non-null  float64
 23  product_width_cm               115289 non-null  float64
 24  product_volume                 115289 non-null  float64
dtypes: datetime64[ns](4), float64(11), int64(1), object(9)
memory usage: 22.9+ MB

In [192]:
merged["delivered_time"] = merged["order_delivered_timestamp"] - merged["order_purchase_timestamp"]

In [194]:
merged

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date,payment_sequential,payment_type,payment_installments,...,seller_id,price,shipping_charges,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_volume,delivered_time
0,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-10 21:25:00,2017-10-18,1.0,credit_card,1.0,...,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,8.72,housewares,500.0,19.0,8.0,13.0,1976.0,8 days 10:29:00
1,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-10 21:25:00,2017-10-18,3.0,voucher,1.0,...,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,8.72,housewares,500.0,19.0,8.0,13.0,1976.0,8 days 10:29:00
2,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-10 21:25:00,2017-10-18,2.0,voucher,1.0,...,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,8.72,housewares,500.0,19.0,8.0,13.0,1976.0,8 days 10:29:00
3,53cdb2fc8bc7dce0b6741e2150273451,af07308b275d755c9edb36a90c618231,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-08-07 15:27:00,2018-08-13,1.0,wallet,1.0,...,289cdb325fb7e7f891c38608bf9e0962,118.70,22.76,toys,400.0,19.0,13.0,19.0,4693.0,13 days 18:46:00
4,47770eb9100c2d0c44946d9cf07ec65d,3a653a41f6f9fc3d2a113cf8398680e8,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-17 18:06:00,2018-09-04,1.0,credit_card,3.0,...,4869f7a5dfa277a7dca6462dcf3b52b2,159.90,19.22,toys,420.0,24.0,19.0,21.0,9576.0,9 days 09:28:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119155,63943bddc261676b46f01ca7ac2f7bd8,da62f9e57a76d978d02ab5362c509660,delivered,2018-02-06 12:58:00,2018-02-06 13:10:00,2018-02-28 17:37:00,2018-03-02,1.0,credit_card,3.0,...,1f9ab4708f3056ede07124aad39a2554,174.90,20.10,baby,4950.0,40.0,10.0,40.0,16000.0,22 days 04:39:00
119156,83c1379a015df1e13d02aae0204711ab,737520a9aad80b3fbbdad19b66b37b30,delivered,2017-08-27 14:46:00,2017-08-27 15:04:00,2017-09-21 11:24:00,2017-09-27,1.0,credit_card,5.0,...,d50d79cb34e38265a8649c383dcffd48,205.99,65.02,toys,13300.0,32.0,90.0,22.0,63360.0,24 days 20:38:00
119157,11c177c8e97725db2631073c19f07b62,5097a5312c8b157bb7be58ae360ef43c,delivered,2018-01-08 21:28:00,2018-01-08 21:36:00,2018-01-25 23:32:00,2018-02-15,1.0,credit_card,4.0,...,a1043bafd471dff536d0c462352beb48,179.99,40.59,computers_accessories,6550.0,20.0,20.0,20.0,8000.0,17 days 02:04:00
119158,11c177c8e97725db2631073c19f07b62,5097a5312c8b157bb7be58ae360ef43c,delivered,2018-01-08 21:28:00,2018-01-08 21:36:00,2018-01-25 23:32:00,2018-02-15,1.0,credit_card,4.0,...,a1043bafd471dff536d0c462352beb48,179.99,40.59,computers_accessories,6550.0,20.0,20.0,20.0,8000.0,17 days 02:04:00
119159,66dea50a8b16d9b4dee7af250b4be1a5,60350aa974b26ff12caad89e55993bd6,delivered,2018-03-08 20:57:00,2018-03-09 11:20:00,2018-03-16 13:08:00,2018-04-03,1.0,debit_card,1.0,...,ececbfcff9804a2d6b40f589df8eef2b,68.50,18.36,toys,150.0,16.0,7.0,15.0,1680.0,7 days 16:11:00

In [196]:
#이상치 처리(IQR 활용)

In [200]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 115289 entries, 0 to 119159
Data columns (total 26 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       115289 non-null  object
 1   customer_id                    115289 non-null  object
 2   order_status                   115289 non-null  object
 3   order_purchase_timestamp       115289 non-null  datetime64[ns]
 4   order_approved_at              115289 non-null  datetime64[ns]
 5   order_delivered_timestamp      115289 non-null  datetime64[ns]
 6   order_estimated_delivery_date  115289 non-null  datetime64[ns]
 7   payment_sequential             115289 non-null  float64
 8   payment_type                   115289 non-null  object
 9   payment_installments           115289 non-null  float64
 10  payment_value                  115289 non-null  float64
 11  customer_zip_code_prefix       115289 non-null  int64
 12  customer_city                  115289 non-null  object
 13  customer_state                 115289 non-null  object
 14  order_item_id                  115289 non-null  float64
 15  product_id                     115289 non-null  object
 16  seller_id                      115289 non-null  object
 17  price                          115289 non-null  float64
 18  shipping_charges               115289 non-null  float64
 19  product_category_name          115289 non-null  object
 20  product_weight_g               115289 non-null  float64
 21  product_length_cm              115289 non-null  float64
 22  product_height_cm              115289 non-null  float64
 23  product_width_cm               115289 non-null  float64
 24  product_volume                 115289 non-null  float64
 25  delivered_time                 115289 non-null  timedelta64[ns]
dtypes: datetime64[ns](4), float64(11), int64(1), object(9), timedelta64[ns](1)
memory usage: 23.7+ MB

In [210]:
#숫자형 컬럼만 추출
numeric_columns = merged.select_dtypes(include=['number'])

#IQR 방법을 적용하여 이상치 탐지
for column in numeric_columns:
    Q1 = numeric_columns[column].quantile(0.25)
    Q3 = numeric_columns[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    print(f"column: {column}")
    print(f"Lower bound: {lower_bound}, Upper bound: {upper_bound}")

    #이상치 필터링
    outliers = merged[(numeric_columns[column] < lower_bound) | (numeric_columns[column] > upper_bound)]
    print("Outliers detected:")
    print(outliers)
    print("\n")

#데이터 특성 분석
#논리 기준
#이상치

column: payment_sequential
Lower bound: 1.0, Upper bound: 1.0
Outliers detected:
                                order_id                       customer_id  \
1       e481f51cbdc54678b7cc49136f2d6af7  7c396fd4830fd04220f754e42b4e5bff
2       e481f51cbdc54678b7cc49136f2d6af7  7c396fd4830fd04220f754e42b4e5bff
11      e69bfb5eb88e0ed6a785585b27e16dbf  299905e3934e9e181bfb2e164dd4b4f8
23      83018ec114eee8641c97e08f7b4e926f  634f09f6075fe9032e6c19609ffe995a
24      83018ec114eee8641c97e08f7b4e926f  634f09f6075fe9032e6c19609ffe995a
...                                  ...                               ...
119047  4bafa54db6b060da198f23f810835969  6e11aa7fefec6405ba35e05a8c0f9b0e
119048  4bafa54db6b060da198f23f810835969  6e11aa7fefec6405ba35e05a8c0f9b0e
119149  9115830be804184b91f5c00f6f49f92d  c716cf2b5b86fb24257cffe9e7969df8
119150  9115830be804184b91f5c00f6f49f92d  c716cf2b5b86fb24257cffe9e7969df8
119151  aa04ef5214580b06b10e2a378300db44  e03dbdf5e56c96b106d8115ac336f47f

       order_status order_purchase_timestamp   order_approved_at  \
1         delivered      2017-10-02 10:56:00 2017-10-02 11:07:00
2         delivered      2017-10-02 10:56:00 2017-10-02 11:07:00
11        delivered      2017-07-29 11:55:00 2017-07-29 12:05:00
23        delivered      2017-10-26 15:54:00 2017-10-26 16:08:00
24        delivered      2017-10-26 15:54:00 2017-10-26 16:08:00
...             ...                      ...                 ...
119047    delivered      2018-04-05 14:46:00 2018-04-05 15:09:00
119048    delivered      2018-04-05 14:46:00 2018-04-05 15:09:00
119149    delivered      2017-10-04 19:57:00 2017-10-04 20:07:00
119150    delivered      2017-10-04 19:57:00 2017-10-04 20:07:00
119151    delivered      2017-01-27 00:30:00 2017-01-27 01:05:00

       order_delivered_timestamp order_estimated_delivery_date  \
1            2017-10-10 21:25:00                    2017-10-18
2            2017-10-10 21:25:00                    2017-10-18
11           2017-08-16 17:14:00                    2017-08-23
23           2017-11-08 22:22:00                    2017-11-23
24           2017-11-08 22:22:00                    2017-11-23
...                          ...                           ...
119047       2018-04-30 21:41:00                    2018-05-14
119048       2018-04-30 21:41:00                    2018-05-14
119149       2017-10-20 20:25:00                    2017-11-07
119150       2017-10-20 20:25:00                    2017-11-07
119151       2017-02-07 13:15:00                    2017-03-17

        payment_sequential payment_type  payment_installments  ...  \
1                      3.0      voucher                   1.0  ...
2                      2.0      voucher                   1.0  ...
11                     2.0      voucher                   1.0  ...
23                     2.0      voucher                   1.0  ...
24                     3.0      voucher                   1.0  ...
...                    ...          ...                   ...  ...
119047                 2.0      voucher                   1.0  ...
119048                 3.0      voucher                   1.0  ...
119149                 2.0      voucher                   1.0  ...
119150                 2.0      voucher                   1.0  ...
119151                 2.0      voucher                   1.0  ...

                               seller_id   price shipping_charges  \
1       3504c0cb71d7fa48d967e0e4c94d59d9   29.99             8.72
2       3504c0cb71d7fa48d967e0e4c94d59d9   29.99             8.72
11      7c67e1448b00f6e969d365cea6b010ab  149.99            19.77
23      70a12e78e608ac31179aea7f8422044b   76.00            16.97
24      70a12e78e608ac31179aea7f8422044b   76.00            16.97
...                                  ...     ...              ...
119047  3df020b72d3d44b3af9d110fa3940b65   49.90            35.71
119048  3df020b72d3d44b3af9d110fa3940b65   49.90            35.71
119149  1caf283236cd69af44cbc09a0a1e7d32   42.11             0.80
119150  1caf283236cd69af44cbc09a0a1e7d32   26.90            36.98
119151  ccc4bbb5f32a6ab2b7066a4130f114e3  370.00            19.43

       product_category_name  product_weight_g product_length_cm  \
1                 housewares             500.0              19.0
2                 housewares             500.0              19.0
11                      toys            9750.0              42.0
23                      toys             325.0              19.0
24                      toys             325.0              19.0
...                      ...               ...               ...
119047                  toys             600.0              17.0
119048                  toys             600.0              17.0
119149                  toys             600.0              48.0
119150                  toys             750.0              26.0
119151                  toys             750.0              38.0

       product_height_cm  product_width_cm  product_volume   delivered_time
1                    8.0              13.0          1976.0  8 days 10:29:00
2                    8.0              13.0          1976.0  8 days 10:29:00
11                  41.0              42.0         72324.0 18 days 05:19:00
23                   8.0              22.0          3344.0 13 days 06:28:00
24                   8.0              22.0          3344.0 13 days 06:28:00
...                  ...               ...             ...              ...
119047              17.0              17.0          4913.0 25 days 06:55:00
119048              17.0              17.0          4913.0 25 days 06:55:00
119149              10.0              48.0         23040.0 16 days 00:28:00
119150              15.0              26.0         10140.0 16 days 00:28:00
119151              12.0              25.0         11400.0 11 days 12:45:00

[4937 rows x 26 columns]


column: payment_installments
Lower bound: -3.5, Upper bound: 8.5
Outliers detected:
                                order_id                       customer_id  \
19      dcb36b511fcac050b97cd5c05de84dc3  ccafc1c3f270410521c3c6f3b249870f
20      403b97836b0c04a622354cf531062e5f  6e26bbeaa107ec34112c64e1ee31c0f5
32      acce194856392f074dbf9dada14d8d82  576ea0cab426cd8a00fad9a9c90a4494
33      acce194856392f074dbf9dada14d8d82  576ea0cab426cd8a00fad9a9c90a4494
48      6ea2f835b4556291ffdc53fa0b3b95e8  3e4fd73f1e86b135b9b121d6abbe9597
...                                  ...                               ...
119110  0fa1fab1d7c1211c824596ed5e111e3c  4b855cb19adce3763ce1af3acc2aae0b
119111  6f756900677a981dd764c34ad85c4b4c  2d8c8c15a3e5119692a3820039ac8761
119127  e8fd20068b9f7e6ec07068bb7537f781  fb9310710003399b031add3e55f34719
119128  e8fd20068b9f7e6ec07068bb7537f781  fb9310710003399b031add3e55f34719
119140  7cc85185736ea7f2d8bc09af7a47cab7  7bb6ca43f478742340256d516d9d86e3

       order_status order_purchase_timestamp   order_approved_at  \
19        delivered      2018-06-07 19:03:00 2018-06-12 23:31:00
20        delivered      2018-01-02 19:00:00 2018-01-02 19:09:00
32        delivered      2018-06-04 00:00:00 2018-06-05 00:35:00
33        delivered      2018-06-04 00:00:00 2018-06-05 00:35:00
48        delivered      2017-11-24 21:27:00 2017-11-25 00:21:00
...             ...                      ...                 ...
119110    delivered      2018-03-13 21:48:00 2018-03-13 22:40:00
119111    delivered      2018-06-26 21:40:00 2018-06-26 21:55:00
119127    delivered      2017-08-10 21:21:00 2017-08-10 21:35:00
119128    delivered      2017-08-10 21:21:00 2017-08-10 21:35:00
119140    delivered      2017-05-15 09:46:00 2017-05-15 10:02:00

       order_delivered_timestamp order_estimated_delivery_date  \
19           2018-06-21 15:34:00                    2018-07-04
20           2018-01-20 01:38:00                    2018-02-06
32           2018-06-16 15:20:00                    2018-07-18
33           2018-06-16 15:20:00                    2018-07-18
48           2017-12-28 18:59:00                    2017-12-21
...                          ...                           ...
119110       2018-04-05 19:59:00                    2018-04-02
119111       2018-06-29 15:28:00                    2018-07-25
119127       2017-08-23 15:36:00                    2017-08-31
119128       2017-08-23 15:36:00                    2017-08-31
119140       2017-05-22 18:05:00                    2017-06-07

        payment_sequential payment_type  payment_installments  ...  \
19                     1.0  credit_card                  10.0  ...
20                     1.0  credit_card                  10.0  ...
32                     1.0  credit_card                  10.0  ...
33                     1.0  credit_card                  10.0  ...
48                     1.0  credit_card                  10.0  ...
...                    ...          ...                   ...  ...
119110                 1.0  credit_card                  10.0  ...
119111                 1.0  credit_card                  10.0  ...
119127                 1.0  credit_card                  10.0  ...
119128                 1.0  credit_card                  10.0  ...
119140                 1.0  credit_card                  10.0  ...

                               seller_id   price shipping_charges  \
19      89a51f50b8095ea78d5768f34c13a76f   132.4            14.05
20      c4af86330efa7a2620772227d2d670c9  1299.0            77.45
32      977f9f63dd360c2a32ece2f93ad6d306    90.9            48.64
33      d673a59aac7a70d8b01e6902bf090a11    39.5            48.64
48      f5f46307a4d15880ca14fab4ad9dfc9b   339.0            17.12
...                                  ...     ...              ...
119110  620c87c171fb2a6dd6e8bb4dec959fc6   249.9            19.63
119111  6b243f80ed07b10f0e8aa0f21a205f3c   124.9            17.06
119127  218d46b86c1881d022bce9c68a7d4b15   356.0            18.12
119128  218d46b86c1881d022bce9c68a7d4b15   356.0            18.12
119140  fe2032dab1a61af8794248c8196565c9   179.9            15.01

       product_category_name  product_weight_g product_length_cm  \
19                      toys             150.0              20.0
20                      toys           20850.0             100.0
32                      toys           10950.0              41.0
33                      toys             350.0              31.0
48                      toys           14300.0              38.0
...                      ...               ...               ...
119110                  toys             750.0              18.0
119111                  toys             800.0              16.0
119127                  toys            2800.0              28.0
119128                  toys            2800.0              28.0
119140                  toys             450.0              23.0

       product_height_cm  product_width_cm  product_volume   delivered_time
19                  20.0              20.0          8000.0 13 days 20:31:00
20                  25.0              50.0        125000.0 17 days 06:38:00
32                  40.0              40.0         65600.0 12 days 15:20:00
33                  10.0              12.0          3720.0 12 days 15:20:00
48                  34.0              34.0         43928.0 33 days 21:32:00
...                  ...               ...             ...              ...
119110              19.0              23.0          7866.0 22 days 22:11:00
119111              16.0              18.0          4608.0  2 days 17:48:00
119127              23.0              23.0         14812.0 12 days 18:15:00
119128              23.0              23.0         14812.0 12 days 18:15:00
119140               8.0              15.0          2760.0  7 days 08:19:00

[7886 rows x 26 columns]


column: payment_value
Lower bound: -131.125, Upper bound: 381.07500000000005
Outliers detected:
                                order_id                       customer_id  \
20      403b97836b0c04a622354cf531062e5f  6e26bbeaa107ec34112c64e1ee31c0f5
45      434d158e96bdd6972ad6e6d73ddcfd22  5f7d7732b351ce851a158528581af05f
62      641fb0752bf5b5940c376b3a8bb9dc52  38cad70d154a4dcc42b598d5c01f7ef1
76      f271576bed568e896f99eb710cd3a6f8  6a0e43f0d7e1b5539e4c58a26ebe35da
77      f271576bed568e896f99eb710cd3a6f8  6a0e43f0d7e1b5539e4c58a26ebe35da
...                                  ...                               ...
119126  3cea94817a51f34aa5937784fb4a3219  0cc2c169569fd06473481e06325a5321
119127  e8fd20068b9f7e6ec07068bb7537f781  fb9310710003399b031add3e55f34719
119128  e8fd20068b9f7e6ec07068bb7537f781  fb9310710003399b031add3e55f34719
119157  11c177c8e97725db2631073c19f07b62  5097a5312c8b157bb7be58ae360ef43c
119158  11c177c8e97725db2631073c19f07b62  5097a5312c8b157bb7be58ae360ef43c

       order_status order_purchase_timestamp   order_approved_at  \
20        delivered      2018-01-02 19:00:00 2018-01-02 19:09:00
45        delivered      2018-06-01 12:23:00 2018-06-05 03:35:00
62        delivered      2017-12-15 00:06:00 2017-12-15 00:14:00
76        delivered      2018-01-07 21:44:00 2018-01-07 21:51:00
77        delivered      2018-01-07 21:44:00 2018-01-07 21:51:00
...             ...                      ...                 ...
119126    delivered      2018-04-01 16:13:00 2018-04-01 16:30:00
119127    delivered      2017-08-10 21:21:00 2017-08-10 21:35:00
119128    delivered      2017-08-10 21:21:00 2017-08-10 21:35:00
119157    delivered      2018-01-08 21:28:00 2018-01-08 21:36:00
119158    delivered      2018-01-08 21:28:00 2018-01-08 21:36:00

       order_delivered_timestamp order_estimated_delivery_date  \
20           2018-01-20 01:38:00                    2018-02-06
45           2018-06-18 21:32:00                    2018-07-17
62           2018-01-03 15:09:00                    2018-01-16
76           2018-01-17 20:26:00                    2018-02-14
77           2018-01-17 20:26:00                    2018-02-14
...                          ...                           ...
119126       2018-04-06 21:32:00                    2018-04-19
119127       2017-08-23 15:36:00                    2017-08-31
119128       2017-08-23 15:36:00                    2017-08-31
119157       2018-01-25 23:32:00                    2018-02-15
119158       2018-01-25 23:32:00                    2018-02-15

        payment_sequential payment_type  payment_installments  ...  \
20                     1.0  credit_card                  10.0  ...
45                     1.0       wallet                   1.0  ...
62                     1.0  credit_card                  10.0  ...
76                     1.0  credit_card                   4.0  ...
77                     1.0  credit_card                   4.0  ...
...                    ...          ...                   ...  ...
119126                 1.0  credit_card                   1.0  ...
119127                 1.0  credit_card                  10.0  ...
119128                 1.0  credit_card                  10.0  ...
119157                 1.0  credit_card                   4.0  ...
119158                 1.0  credit_card                   4.0  ...

                               seller_id    price shipping_charges  \
20      c4af86330efa7a2620772227d2d670c9  1299.00            77.45
45      a5cba26a62b8b4d0145b68b841e62e7f   445.00            63.17
62      b33e7c55446eabf8fe1a42d037ac7d6d   369.00            17.33
76      76d64c4aca3a7baf218bf93ef7fa768d   329.90            82.48
77      76d64c4aca3a7baf218bf93ef7fa768d   329.90            82.48
...                                  ...      ...              ...
119126  edb1ef5e36e0c8cd84eb3c9b003e486d   439.65            20.96
119127  218d46b86c1881d022bce9c68a7d4b15   356.00            18.12
119128  218d46b86c1881d022bce9c68a7d4b15   356.00            18.12
119157  a1043bafd471dff536d0c462352beb48   179.99            40.59
119158  a1043bafd471dff536d0c462352beb48   179.99            40.59

        product_category_name  product_weight_g product_length_cm  \
20                       toys           20850.0             100.0
45              health_beauty             683.0              29.0
62              watches_gifts             394.0              17.0
76                       toys           10000.0              30.0
77                       toys           10000.0              30.0
...                       ...               ...               ...
119126                   toys             300.0              20.0
119127                   toys            2800.0              28.0
119128                   toys            2800.0              28.0
119157  computers_accessories            6550.0              20.0
119158  computers_accessories            6550.0              20.0

       product_height_cm  product_width_cm  product_volume   delivered_time
20                  25.0              50.0        125000.0 17 days 06:38:00
45                  15.0              22.0          9570.0 17 days 09:09:00
62                  11.0              14.0          2618.0 19 days 15:03:00
76                  20.0              30.0         18000.0  9 days 22:42:00
77                  20.0              30.0         18000.0  9 days 22:42:00
...                  ...               ...             ...              ...
119126               9.0              15.0          2700.0  5 days 05:19:00
119127              23.0              23.0         14812.0 12 days 18:15:00
119128              23.0              23.0         14812.0 12 days 18:15:00
119157              20.0              20.0          8000.0 17 days 02:04:00
119158              20.0              20.0          8000.0 17 days 02:04:00

[9256 rows x 26 columns]


column: customer_zip_code_prefix
Lower bound: -59535.0, Upper bound: 129385.0
Outliers detected:
Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_timestamp, order_estimated_delivery_date, payment_sequential, payment_type, payment_installments, payment_value, customer_zip_code_prefix, customer_city, customer_state, order_item_id, product_id, seller_id, price, shipping_charges, product_category_name, product_weight_g, product_length_cm, product_height_cm, product_width_cm, product_volume, delivered_time]
Index: []

[0 rows x 26 columns]


column: order_item_id
Lower bound: 1.0, Upper bound: 1.0
Outliers detected:
                                order_id                       customer_id  \
14      e6ce16cb79ec1d90b1da9085a6118aeb  f2a85dec752b8517b5e58a06ff3cd937
33      acce194856392f074dbf9dada14d8d82  576ea0cab426cd8a00fad9a9c90a4494
61      9faeb9b2746b9d7526aef5acb08e2aa0  c77154776ead8e798c2d684205938f71
67      66e4624ae69e7dc89bd50222b59f581f  ddf60e20e6e262e2136801ce5cd628b0
75      688052146432ef8253587b930b01a06d  0e764fc1a13e47e900c3d59a989753e8
...                                  ...                               ...
119109  b3112ca67f3afd4e20cf2ee91fc4f804  f690f0caffab80b6f849f08ba1692925
119128  e8fd20068b9f7e6ec07068bb7537f781  fb9310710003399b031add3e55f34719
119148  9115830be804184b91f5c00f6f49f92d  c716cf2b5b86fb24257cffe9e7969df8
119150  9115830be804184b91f5c00f6f49f92d  c716cf2b5b86fb24257cffe9e7969df8
119158  11c177c8e97725db2631073c19f07b62  5097a5312c8b157bb7be58ae360ef43c

       order_status order_purchase_timestamp   order_approved_at  \
14        delivered      2017-05-16 19:41:00 2017-05-16 19:50:00
33        delivered      2018-06-04 00:00:00 2018-06-05 00:35:00
61        delivered      2018-07-26 14:39:00 2018-07-26 14:55:00
67        delivered      2018-03-09 14:50:00 2018-03-09 15:40:00
75        delivered      2018-04-22 08:48:00 2018-04-24 18:25:00
...             ...                      ...                 ...
119109    delivered      2018-08-02 22:46:00 2018-08-02 23:04:00
119128    delivered      2017-08-10 21:21:00 2017-08-10 21:35:00
119148    delivered      2017-10-04 19:57:00 2017-10-04 20:07:00
119150    delivered      2017-10-04 19:57:00 2017-10-04 20:07:00
119158    delivered      2018-01-08 21:28:00 2018-01-08 21:36:00


In [212]:
merged.nunique()

order_id                         96139
customer_id                      93041
order_status                         2
order_purchase_timestamp         86076
order_approved_at                49330
order_delivered_timestamp        75427
order_estimated_delivery_date      444
payment_sequential                  26
payment_type                         4
payment_installments                24
payment_value                    28483
customer_zip_code_prefix         14881
customer_city                     4081
customer_state                      27
order_item_id                       21
product_id                       32047
seller_id                         2961
price                             5835
shipping_charges                  6917
product_category_name               70
product_weight_g                  2170
product_length_cm                   99
product_height_cm                  102
product_width_cm                    94
product_volume                    4442
delivered_time                   34908
dtype: int64

In [214]:
merged = pd.get_dummies(merged, columns = ["payment_type"])

In [218]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 115289 entries, 0 to 119159
Data columns (total 29 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       115289 non-null  object
 1   customer_id                    115289 non-null  object
 2   order_status                   115289 non-null  object
 3   order_purchase_timestamp       115289 non-null  datetime64[ns]
 4   order_approved_at              115289 non-null  datetime64[ns]
 5   order_delivered_timestamp      115289 non-null  datetime64[ns]
 6   order_estimated_delivery_date  115289 non-null  datetime64[ns]
 7   payment_sequential             115289 non-null  float64
 8   payment_installments           115289 non-null  float64
 9   payment_value                  115289 non-null  float64
 10  customer_zip_code_prefix       115289 non-null  int64
 11  customer_city                  115289 non-null  object
 12  customer_state                 115289 non-null  object
 13  order_item_id                  115289 non-null  float64
 14  product_id                     115289 non-null  object
 15  seller_id                      115289 non-null  object
 16  price                          115289 non-null  float64
 17  shipping_charges               115289 non-null  float64
 18  product_category_name          115289 non-null  object
 19  product_weight_g               115289 non-null  float64
 20  product_length_cm              115289 non-null  float64
 21  product_height_cm              115289 non-null  float64
 22  product_width_cm               115289 non-null  float64
 23  product_volume                 115289 non-null  float64
 24  delivered_time                 115289 non-null  timedelta64[ns]
 25  payment_type_credit_card       115289 non-null  bool
 26  payment_type_debit_card        115289 non-null  bool
 27  payment_type_voucher           115289 non-null  bool
 28  payment_type_wallet            115289 non-null  bool
dtypes: bool(4), datetime64[ns](4), float64(11), int64(1), object(8), timedelta64[ns](1)
memory usage: 23.3+ MB

In [222]:
merged = pd.get_dummies(merged, columns = ["product_category_name"])

In [226]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 115289 entries, 0 to 119159
Data columns (total 98 columns):
 #   Column                                                         Non-Null Count   Dtype
---  ------                                                         --------------   -----
 0   order_id                                                       115289 non-null  object
 1   customer_id                                                    115289 non-null  object
 2   order_status                                                   115289 non-null  object
 3   order_purchase_timestamp                                       115289 non-null  datetime64[ns]
 4   order_approved_at                                              115289 non-null  datetime64[ns]
 5   order_delivered_timestamp                                      115289 non-null  datetime64[ns]
 6   order_estimated_delivery_date                                  115289 non-null  datetime64[ns]
 7   payment_sequential                                             115289 non-null  float64
 8   payment_installments                                           115289 non-null  float64
 9   payment_value                                                  115289 non-null  float64
 10  customer_zip_code_prefix                                       115289 non-null  int64
 11  customer_city                                                  115289 non-null  object
 12  customer_state                                                 115289 non-null  object
 13  order_item_id                                                  115289 non-null  float64
 14  product_id                                                     115289 non-null  object
 15  seller_id                                                      115289 non-null  object
 16  price                                                          115289 non-null  float64
 17  shipping_charges                                               115289 non-null  float64
 18  product_weight_g                                               115289 non-null  float64
 19  product_length_cm                                              115289 non-null  float64
 20  product_height_cm                                              115289 non-null  float64
 21  product_width_cm                                               115289 non-null  float64
 22  product_volume                                                 115289 non-null  float64
 23  delivered_time                                                 115289 non-null  timedelta64[ns]
 24  payment_type_credit_card                                       115289 non-null  bool
 25  payment_type_debit_card                                        115289 non-null  bool
 26  payment_type_voucher                                           115289 non-null  bool
 27  payment_type_wallet                                            115289 non-null  bool
 28  product_category_name_agro_industry_and_commerce               115289 non-null  bool
 29  product_category_name_air_conditioning                         115289 non-null  bool
 30  product_category_name_art                                      115289 non-null  bool
 31  product_category_name_arts_and_craftmanship                    115289 non-null  bool
 32  product_category_name_audio                                    115289 non-null  bool
 33  product_category_name_auto                                     115289 non-null  bool
 34  product_category_name_baby                                     115289 non-null  bool
 35  product_category_name_bed_bath_table                           115289 non-null  bool
 36  product_category_name_books_general_interest                   115289 non-null  bool
 37  product_category_name_books_imported                           115289 non-null  bool
 38  product_category_name_books_technical                          115289 non-null  bool
 39  product_category_name_christmas_supplies                       115289 non-null  bool
 40  product_category_name_cine_photo                               115289 non-null  bool
 41  product_category_name_computers                                115289 non-null  bool
 42  product_category_name_computers_accessories                    115289 non-null  bool
 43  product_category_name_consoles_games                           115289 non-null  bool
 44  product_category_name_construction_tools_construction          115289 non-null  bool
 45  product_category_name_construction_tools_lights                115289 non-null  bool
 46  product_category_name_construction_tools_safety                115289 non-null  bool
 47  product_category_name_cool_stuff                               115289 non-null  bool
 48  product_category_name_costruction_tools_garden                 115289 non-null  bool
 49  product_category_name_costruction_tools_tools                  115289 non-null  bool
 50  product_category_name_diapers_and_hygiene                      115289 non-null  bool
 51  product_category_name_drinks                                   115289 non-null  bool
 52  product_category_name_dvds_blu_ray                             115289 non-null  bool
 53  product_category_name_electronics                              115289 non-null  bool
 54  product_category_name_fashio_female_clothing                   115289 non-null  bool
 55  product_category_name_fashion_bags_accessories                 115289 non-null  bool
 56  product_category_name_fashion_childrens_clothes                115289 non-null  bool
 57  product_category_name_fashion_male_clothing                    115289 non-null  bool
 58  product_category_name_fashion_shoes                            115289 non-null  bool
 59  product_category_name_fashion_sport                            115289 non-null  bool
 60  product_category_name_fashion_underwear_beach                  115289 non-null  bool
 61  product_category_name_fixed_telephony                          115289 non-null  bool
 62  product_category_name_flowers                                  115289 non-null  bool
 63  product_category_name_food                                     115289 non-null  bool
 64  product_category_name_food_drink                               115289 non-null  bool
 65  product_category_name_furniture_bedroom                        115289 non-null  bool
 66  product_category_name_furniture_decor                          115289 non-null  bool
 67  product_category_name_furniture_living_room                    115289 non-null  bool
 68  product_category_name_furniture_mattress_and_upholstery        115289 non-null  bool
 69  product_category_name_garden_tools                             115289 non-null  bool
 70  product_category_name_health_beauty                            115289 non-null  bool
 71  product_category_name_home_appliances                          115289 non-null  bool
 72  product_category_name_home_appliances_2                        115289 non-null  bool
 73  product_category_name_home_comfort_2                           115289 non-null  bool
 74  product_category_name_home_confort                             115289 non-null  bool
 75  product_category_name_home_construction                        115289 non-null  bool
 76  product_category_name_housewares                               115289 non-null  bool
 77  product_category_name_industry_commerce_and_business           115289 non-null  bool
 78  product_category_name_kitchen_dining_laundry_garden_furniture  115289 non-null  bool
 79  product_category_name_la_cuisine                               115289 non-null  bool
 80  product_category_name_luggage_accessories                      115289 non-null  bool
 81  product_category_name_market_place                             115289 non-null  bool
 82  product_category_name_music                                    115289 non-null  bool
 83  product_category_name_musical_instruments                      115289 non-null  bool
 84  product_category_name_office_furniture                         115289 non-null  bool
 85  product_category_name_party_supplies                           115289 non-null  bool
 86  product_category_name_perfumery                                115289 non-null  bool
 87  product_category_name_pet_shop                                 115289 non-null  bool
 88  product_category_name_security_and_services                    115289 non-null  bool
 89  product_category_name_signaling_and_security                   115289 non-null  bool
 90  product_category_name_small_appliances                         115289 non-null  bool
 91  product_category_name_small_appliances_home_oven_and_coffee    115289 non-null  bool
 92  product_category_name_sports_leisure                           115289 non-null  bool
 93  product_category_name_stationery                               115289 non-null  bool
 94  product_category_name_tablets_printing_image                   115289 non-null  bool
 95  product_category_name_telephony                                115289 non-null  bool
 96  product_category_name_toys                                     115289 non-null  bool
 97  product_category_name_watches_gifts                            115289 non-null  bool
dtypes: bool(74), datetime64[ns](4), float64(11), int64(1), object(7), timedelta64[ns](1)
memory usage: 30.1+ MB

In [228]:
from sklearn.preprocessing import StandardScaler

In [230]:
scaler = StandardScaler()

In [236]:
numeric_columns = merged.select_dtypes(include=['number'])
numeric_columns.info()
#scaled_data = scaler.fit_transform(numeric_columns)

<class 'pandas.core.frame.DataFrame'>
Index: 115289 entries, 0 to 119159
Data columns (total 13 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   payment_sequential        115289 non-null  float64
 1   payment_installments      115289 non-null  float64
 2   payment_value             115289 non-null  float64
 3   customer_zip_code_prefix  115289 non-null  int64
 4   order_item_id             115289 non-null  float64
 5   price                     115289 non-null  float64
 6   shipping_charges          115289 non-null  float64
 7   product_weight_g          115289 non-null  float64
 8   product_length_cm         115289 non-null  float64
 9   product_height_cm         115289 non-null  float64
 10  product_width_cm          115289 non-null  float64
 11  product_volume            115289 non-null  float64
 12  delivered_time            115289 non-null  timedelta64[ns]
dtypes: float64(11), int64(1), timedelta64[ns](1)
memory usage: 12.3 MB

In [238]:
numeric_columns = merged.select_dtypes(include=['number'])
scaled_data = scaler.fit_transform(merged[["delivered_time"]])

In [240]:
scaled_data

array([[-0.4286692 ],
       [-0.4286692 ],
       [-0.4286692 ],
       ...,
       [ 0.48821231],
       [ 0.48821231],
       [-0.50949906]])

In [242]:
merged["delivered_time"] = scaled_data

In [246]:
merged["delivered_time"]

0        -0.428669
1        -0.428669
2        -0.428669
3         0.137950
4        -0.327153
            ...
119155    1.029655
119156    1.312265
119157    0.488212
119158    0.488212
119159   -0.509499
Name: delivered_time, Length: 115289, dtype: float64