In [1]:
#불러온 데이터 미리보기 및 기본 정보 확인

In [3]:
#데이터 미리보기

In [5]:
#head() 함수는 데이터 프레임의 상위 몇 개의 행을 미리보기함. 기본적으로 5개 행을 보여줌.
import pandas as pd

#CSV 파일 불러오기
df = pd.read_csv('test.csv')

# 상위 5개 행 미리보기
print(df.head())

   상권번호       상권명  시도코드    시도명  시군구코드 시군구명  상권좌표수  \
0  9138     공덕역_1    11  서울특별시  11440  마포구     19
1  9139     공덕역_2    11  서울특별시  11440  마포구     25
2  9140  디지털미디어시티    11  서울특별시  11440  마포구     44
3  9141     마포역_1    11  서울특별시  11440  마포구     54
4  9142     마포역_2    11  서울특별시  11440  마포구     44

                                                상권좌표     데이터기준일자
0  126.951086855113,37.5437086852164|126.95108685...  2020.12.31
1  126.95321229004,37.5466265375676|126.953212291...  2020.12.31
2  126.887123962571,37.5834487598235|126.88655960...  2020.12.31
3  126.949848889864,37.5421381698383|126.94983757...  2020.12.31
4  126.947814199015,37.5432207096313|126.94780571...  2020.12.31

In [7]:
#특정 개수의 행을 미리보기
print(df.head(10))

   상권번호       상권명  시도코드    시도명  시군구코드 시군구명  상권좌표수  \
0  9138     공덕역_1    11  서울특별시  11440  마포구     19
1  9139     공덕역_2    11  서울특별시  11440  마포구     25
2  9140  디지털미디어시티    11  서울특별시  11440  마포구     44
3  9141     마포역_1    11  서울특별시  11440  마포구     54
4  9142     마포역_2    11  서울특별시  11440  마포구     44
5  9143     신촌역_1    11  서울특별시  11440  마포구     25
6  9144   홍대입구역_1    11  서울특별시  11440  마포구     28
7  9145   홍대입구역_2    11  서울특별시  11440  마포구     33
8  9146   홍대입구역_3    11  서울특별시  11440  마포구     39
9  9147     홍익대학교    11  서울특별시  11440  마포구     81

                                                상권좌표     데이터기준일자
0  126.951086855113,37.5437086852164|126.95108685...  2020.12.31
1  126.95321229004,37.5466265375676|126.953212291...  2020.12.31
2  126.887123962571,37.5834487598235|126.88655960...  2020.12.31
3  126.949848889864,37.5421381698383|126.94983757...  2020.12.31
4  126.947814199015,37.5432207096313|126.94780571...  2020.12.31
5  126.936222504861,37.5551327655308|126.93281773...  2020.12.31
6  126.917547497767,37.554037541561|126.917550337...  2020.12.31
7  126.918989448392,37.5574916071601|126.91899227...  2020.12.31
8  126.920849965031,37.5559994971365|126.92084147...  2020.12.31
9  126.925081046599,37.5575745371267|126.92508104...  2020.12.31

In [9]:
#tail()로 하위 데이터 미리보기
#tail() 함수는 하위 몇 개의 행을 미리보기 함.

print(df.tail())

       상권번호       상권명  시도코드    시도명  시군구코드 시군구명  상권좌표수  \
1162  10372  동아대부민캠퍼스    26  부산광역시  26140   서구      6
1163  10373     동대신동역    26  부산광역시  26140   서구      5
1164  10374     동아대병원    26  부산광역시  26140   서구      7
1165  10375     하단역 3    26  부산광역시  26380  사하구      7
1166  10376     다대포항역    26  부산광역시  26380  사하구     13

                                                   상권좌표     데이터기준일자
1162  129.021141559118,35.103350139431|129.021257888...  2020.12.31
1163  129.015235871206,35.1120140488436|129.01703930...  2020.12.31
1164  129.016351590164,35.1194662001032|129.01652337...  2020.12.31
1165  128.968231685786,35.106090309415|128.961760672...  2020.12.31
1166  128.971395098319,35.0561584604433|128.97099481...  2020.12.31

In [11]:
#특정 개수의 하위 행을 보고 싶다면?
print(df.tail(10))

       상권번호       상권명  시도코드    시도명  시군구코드 시군구명  상권좌표수  \
1157  10367      원평동3    47   경상북도  47190  구미시      9
1158  10368  아주대삼거리_4    41    경기도  41110  수원시     16
1159  10369       기흥역    41    경기도  41460  용인시      8
1160  10370      유천택지    42    강원도  42150  강릉시     10
1161  10371   부산대병원상권    26  부산광역시  26140   서구      6
1162  10372  동아대부민캠퍼스    26  부산광역시  26140   서구      6
1163  10373     동대신동역    26  부산광역시  26140   서구      5
1164  10374     동아대병원    26  부산광역시  26140   서구      7
1165  10375     하단역 3    26  부산광역시  26380  사하구      7
1166  10376     다대포항역    26  부산광역시  26380  사하구     13

                                                   상권좌표     데이터기준일자
1157  128.335342195416,36.1253834158196|128.33538600...  2020.12.31
1158  127.043895619119,37.2773494583136|127.04403305...  2020.12.31
1159  127.115788622917,37.279513845993|127.114213513...  2020.12.31
1160  128.871493197865,37.7580190438181|128.86795143...  2020.12.31
1161  129.017720211459,35.1033485338574|129.01753802...  2020.12.31
1162  129.021141559118,35.103350139431|129.021257888...  2020.12.31
1163  129.015235871206,35.1120140488436|129.01703930...  2020.12.31
1164  129.016351590164,35.1194662001032|129.01652337...  2020.12.31
1165  128.968231685786,35.106090309415|128.961760672...  2020.12.31
1166  128.971395098319,35.0561584604433|128.97099481...  2020.12.31

In [14]:
#데이터프레임의 기본 정보 확인하기

In [18]:
#info()로 데이터프레임의 요약 정보 확인
# info() 함수는 데이터프레임의 전체 구조를 한 눈에 보여줌.
# 각 열의 데이터 타입과 널 값 여부를 확인할 수 있음.

In [20]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1167 entries, 0 to 1166
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   상권번호     1167 non-null   int64
 1   상권명      1167 non-null   object
 2   시도코드     1167 non-null   int64
 3   시도명      1167 non-null   object
 4   시군구코드    1167 non-null   int64
 5   시군구명     1167 non-null   object
 6   상권좌표수    1167 non-null   int64
 7   상권좌표     1167 non-null   object
 8   데이터기준일자  1167 non-null   object
dtypes: int64(4), object(5)
memory usage: 82.2+ KB
None

In [23]:
#describe()로 주요 통계 정보 확인
#describe() 함수는 숫자형 데이터에 대한 주요 통계 정보를 제공함.
#평균, 표준편차, 최소값, 최대값 등을 확인할 수 있음.

In [25]:
print(df.describe())

               상권번호         시도코드         시군구코드        상권좌표수
count   1167.000000  1167.000000   1167.000000  1167.000000
mean    9739.299057    32.358183  32685.646958    24.050557
std      352.291504    13.255578  13211.663933    15.660529
min     9138.000000    11.000000  11110.000000     4.000000
25%     9435.500000    26.000000  26290.000000    13.000000
50%     9733.000000    41.000000  41110.000000    20.000000
75%    10037.500000    43.000000  43790.000000    32.000000
max    10376.000000    50.000000  50130.000000   127.000000

In [27]:
#특정 열에 대한 통계를 보고 싶다면?
print(df['상권번호'].describe())

count     1167.000000
mean      9739.299057
std        352.291504
min       9138.000000
25%       9435.500000
50%       9733.000000
75%      10037.500000
max      10376.000000
Name: 상권번호, dtype: float64

In [38]:
#columns와 index로 열과 행 정보 확인
# 데이터프레임의 열 이름과 행 인덱스를 확인할 수 있음.

print(df.columns)
print("줄 구분")
print(df.index)

Index(['상권번호', '상권명', '시도코드', '시도명', '시군구코드', '시군구명', '상권좌표수', '상권좌표',
       '데이터기준일자'],
      dtype='object')
줄 구분
RangeIndex(start=0, stop=1167, step=1)

In [41]:
#데이터프레임의 개별 데이터 롹인하기

In [43]:
#loc[]로 헹과 열의 위치를 지정하여 접근하기
#loc[]은 라벨(인덱스, 컬럼명)을 사용해 특정 데이터를 조회.

In [49]:
#특정 행 조회
print(df.loc[0]) #첫 번째 행 조회

상권번호                                                    9138
상권명                                                    공덕역_1
시도코드                                                      11
시도명                                                    서울특별시
시군구코드                                                  11440
시군구명                                                     마포구
상권좌표수                                                     19
상권좌표       126.951086855113,37.5437086852164|126.95108685...
데이터기준일자                                           2020.12.31
Name: 0, dtype: object

In [57]:
#특정 행과 열 조회
print(df.loc[0, '상권명']) # 첫 번쨰 행의 '상권명' 열 데이터

공덕역_1

In [59]:
#iloc[]로 행과 열의 위치 인덱스를 사용해 데이터를 조회.
# iloc[]은 정수 인덱스를 사용해 데이터를 조회.

#첫 번째 행 조회
print(df.iloc[0])

상권번호                                                    9138
상권명                                                    공덕역_1
시도코드                                                      11
시도명                                                    서울특별시
시군구코드                                                  11440
시군구명                                                     마포구
상권좌표수                                                     19
상권좌표       126.951086855113,37.5437086852164|126.95108685...
데이터기준일자                                           2020.12.31
Name: 0, dtype: object

In [63]:
#첫 번째 행의 두 번째 열 데이터 조회
print(df.iloc[0,1])

공덕역_1

In [66]:
#특정 열이나 행 전체를 선택하기

In [72]:
#특정 열 전체를 선택
print(df['상권명'])

0          공덕역_1
1          공덕역_2
2       디지털미디어시티
3          마포역_1
4          마포역_2
          ...
1162    동아대부민캠퍼스
1163       동대신동역
1164       동아대병원
1165       하단역 3
1166       다대포항역
Name: 상권명, Length: 1167, dtype: object

In [74]:
#여러 열을 선택하고 싶다면?
print(df[['상권명','시도명']])

           상권명    시도명
0        공덕역_1  서울특별시
1        공덕역_2  서울특별시
2     디지털미디어시티  서울특별시
3        마포역_1  서울특별시
4        마포역_2  서울특별시
...        ...    ...
1162  동아대부민캠퍼스  부산광역시
1163     동대신동역  부산광역시
1164     동아대병원  부산광역시
1165     하단역 3  부산광역시
1166     다대포항역  부산광역시

[1167 rows x 2 columns]

In [76]:
#특정 행 전체를 선택하려면 loc[] 또는 iloc[]을 사용할 것.

In [ ]:
#요약
#info()와 describe()를 사용해 데이터프레임의 구조와 주요 통계 정보를 확인할 수 있음.
#loc[], iloc[]을 사용헤 개별 데이터나 특정 행과 열의 값을 쉽게 조회할 수 있음.